### ISSUE TITLE
Problem with Files permissions after update to 1.6.2

### ISSUE THREAD

**Issue by tillilab** [modxcms/Gallery#25]
After updating to 1.6.2 many of my sites give me "internal error" when using the gallery component.
Usually I can solve this problem with the "repair permission" tool of the hosting, but some hosting doesn't have this tool..

It seems that some file (i.e. assets/components/gallery/connectors.php) need to be executable, but I've not been able to specify the exact list of files involved.

In one case I can't create new album: in the error.log I can't find anything interesting, but with the browser console, when I try to create a new album i.e. I have the following errors:

Uncaught TypeError: undefined is not a function ext-all.js:7
create ext-all.js:7
Ext.extend.load modx.js:74
Ext.extend.createAlbum album.tree.js:39
Ext.applyIf.tbar.handler album.tree.js:10
Ext.Button.Ext.extend.onClick ext-all.js:7
I ext-all.js:7

Thanks
